[package]
name = "rairstream"
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"
authors = ["bytecolt"]
repository = ""
rust-version = "1.85"

[dependencies]
anyhow = "1.0.100"
mdns-sd = "0.19.0"
serde = { version = "1.0.228", features = ["derive"] }
tao = "0.35.0"
thiserror = "2.0.17"
tracing = "0.1.41"
tray-icon = "0.22.0"

[target.'cfg(windows)'.dependencies]
wasapi = "0.23.0"

[dev-dependencies]
serde_json = "1.0"

[lints.clippy]
all = { level = "warn", priority = -1 }
pedantic = { level = "warn", priority = -1 }
module_name_repetitions = "allow"
missing_errors_doc = "allow"
missing_panics_doc = "allow"

[lints.rust]
unsafe_code = "forbid"
